all: allee
apt: apartment
av: avenue
ave: avenue
bat: batiment
bd: boulevard
bld: boulevard
bldg: building
blvd: boulevard
cir: circle
ct: court
dept: department
dr: drive
etg: etage
expy: expressway
fl: floor
hwy: highway
imp: impasse
ln: lane
'no': number
ofc: office
pkwy: parkway
pl: place
r: rue
rd: road
res: residence
rm: room
rt: route
sq: square
st: street
ste: suite
ter: terrace
way: way
