co: company
company: company
corp: corporation
corporation: corporation
eurl: eurl
gie: gie
gmbh: gmbh
inc: incorporated
incorporated: incorporated
limited: limited
llc: llc
llp: llp
ltd: limited
plc: plc
private: private
pvt: private
pvt ltd: private limited
s.a: sa
s.a.r.l: sarl
s.a.s: sas
sa: sa
sarl: sarl
sas: sas
sasu: sasu
sci: sci
snc: snc
